version: "3"
services:
  springdb:
    image: mongo:latest
    container_name: "springdbb"
    ports:
      - 27017:27017
    networks:
      - default
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    command: --auth # Enable authentication

  Spring:
    image: fares123456/springbootapp:latest
    container_name: springbootapp
    ports:
      - 8099:8081
    links:
      - springdb
    depends_on:
      - springdb
    networks:
      - default

volumes:
  mongo-data:
