version: "3"
services:
  springdb:
    image: mongo:latest
    container_name: "springdbb"
    ports:
      - 27017:27017
    networks:
      - my_network
    volumes:
      - mongo-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  springbootapp:
    image: fares123456/springbootapp:latest
    container_name: springbootapp
    ports:
      - 8099:8081
    networks:
      - my_network

volumes:
  mongo-data:

networks:
  my_network:
    external: true
